import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import React from "react";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Saurav",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
